version: '3.7'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client-server
    container_name: my-client-server
    command: npm run dev
    volumes:
      # bind mounting entire project folder to container for watcher detection
      - ./client:/usr/app/client
      # node_modules gets its own volume for all containers to share
      - node_modules_client:/usr/app/client/node_modules
    ports:
      - "3000:3000"
    networks:
      - linkednetwork  

volumes:
    node_modules_client:

networks:
  linkednetwork: